#!/usr/bin/env tsx
/**
 * sync-abis.ts
 * Reads compiled Foundry artifacts + deployment addresses for ALL networks,
 * writes type-safe ABI files to lib/abis/ and updates lib/contracts.ts
 * with the chain-keyed address map.
 *
 * Run: pnpm sync:abis
 *
 * After mainnet deploy: the qie_mainnet.json file will be present and this
 * script will populate the 1990 entry in CONTRACT_ADDRESSES automatically.
 */

import fs from 'node:fs'
import path from 'node:path'

const ROOT      = path.resolve(__dirname, '../..')
const OUT_DIR   = path.join(ROOT, 'contracts/out')
const DEPLOY_DIR = path.join(ROOT, 'contracts/deployments')
const ABIS_DIR  = path.join(__dirname, '../lib/abis')
const CONTRACTS_FILE = path.join(__dirname, '../lib/contracts.ts')

// Network definitions — add more here as chains are added
const NETWORKS = [
  { file: 'anvil.json',        chainId: 31337, label: 'Anvil (local)' },
  { file: 'qie_testnet.json',  chainId: 1983,  label: 'QIE Testnet' },
  { file: 'qie_mainnet.json',  chainId: 1990,  label: 'QIE Mainnet' },
] as const

/**
 * Placeholder used only when contracts/deployments/qie_mainnet.json is absent.
 * The real value always comes from the deployment file.
 *
 * Deliberately NOT described as "the canonical stablecoin" — that has to be
 * verified on-chain before a launch, and the generator has no way to check it.
 */
const MAINNET_QUSD_PLACEHOLDER = '0x3F43DA82eC9A4f5285F10FaF1F26EcA7319E5DA5'

/**
 * Known test tokens. If a deployment points at one of these on mainnet the
 * generator says so in the output instead of labelling it as the real thing.
 */
const KNOWN_TEST_TOKENS: Record<string, string> = {
  '0x9b5d310a92f05c3714e4163e43f226c7a6fb0827': 'MockQUSD — owner-mintable test token, NOT redeemable',
}

interface DeployedContracts {
  TimelockController: string
  KYCRegistry: string
  EscrowVault: string
  RemitChain: string
}
interface DeploymentConfig {
  qusd: string
  feeTreasury: string
  initialFeeBps: number
}
interface DeploymentFile {
  contracts: DeployedContracts
  config: DeploymentConfig
  /** Block the contracts went live at. Absent in pre-2026-08 deployment files. */
  deployedAtBlock?: number
}

function readAbi(contractDir: string, contractName: string): unknown[] {
  const jsonPath = path.join(OUT_DIR, contractDir, `${contractName}.json`)
  if (!fs.existsSync(jsonPath)) {
    throw new Error(`Artifact not found: ${jsonPath}`)
  }
  const artifact = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'))
  return artifact.abi
}

interface AbiFragment { type: string; name?: string; inputs?: Array<{ type: string }> }

/**
 * Merge the `error` fragments of called contracts into a caller's ABI, so a
 * revert that originates downstream can still be decoded by the client.
 * De-duplicated on the error's canonical signature.
 */
function withInheritedErrors(base: unknown[], sources: unknown[][]): unknown[] {
  const signature = (f: AbiFragment) =>
    `${f.name}(${(f.inputs ?? []).map(i => i.type).join(',')})`

  const seen = new Set(
    (base as AbiFragment[]).filter(f => f.type === 'error').map(signature),
  )
  const merged = [...base]

  for (const source of sources) {
    for (const fragment of source as AbiFragment[]) {
      if (fragment.type !== 'error') continue
      const sig = signature(fragment)
      if (seen.has(sig)) continue
      seen.add(sig)
      merged.push(fragment)
    }
  }
  return merged
}

function writeAbiFile(name: string, abi: unknown[]): void {
  const content = `// Auto-generated by scripts/sync-abis.ts — DO NOT EDIT MANUALLY
// Source: contracts/out/${name}.sol/${name}.json

export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;
`
  fs.writeFileSync(path.join(ABIS_DIR, `${name}.ts`), content, 'utf-8')
  console.log(`  ✓ lib/abis/${name}.ts`)
}

function main(): void {
  fs.mkdirSync(ABIS_DIR, { recursive: true })

  console.log('\n🔄 Syncing ABIs from contracts/out/...\n')

  // Extract and write the three core contract ABIs
  const remitChainAbi = readAbi('RemitChain.sol', 'RemitChain')
  const escrowVaultAbi = readAbi('EscrowVault.sol', 'EscrowVault')
  const kycRegistryAbi = readAbi('KYCRegistry.sol', 'KYCRegistry')

  // RemitChain is a router: it calls KYCRegistry and EscrowVault, and their
  // reverts bubble up through it. Solidity only emits an error into a
  // contract's ABI if that contract itself references it, so `KYCRequired`,
  // `DailyLimitExceeded`, `TransferIdCollision` and friends were absent from
  // RemitChain's ABI — and viem cannot decode a custom error it has no
  // definition for.
  //
  // The practical effect was that the send page's error mapping
  // (`raw.includes('KYCRequired')`) could never match: a user who had not
  // completed verification, or who hit their daily limit, saw an undecoded hex
  // blob instead of an explanation. Merging the callees' error fragments in
  // makes those reverts decodable at the call site that actually produces them.
  writeAbiFile('RemitChain', withInheritedErrors(remitChainAbi, [escrowVaultAbi, kycRegistryAbi]))
  writeAbiFile('EscrowVault', escrowVaultAbi)
  writeAbiFile('KYCRegistry', kycRegistryAbi)

  // Minimal ERC20 ABI (only what RemitChain frontend uses)
  const erc20Abi = [
    { type: 'function', name: 'balanceOf', inputs: [{ name: 'account', type: 'address' }], outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view' },
    { type: 'function', name: 'approve', inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ name: '', type: 'bool' }], stateMutability: 'nonpayable' },
    // `transfer` and `transferFrom` were missing from this list, so the faucet
    // route had to declare a second, private ERC-20 ABI to call transfer at all.
    { type: 'function', name: 'transfer', inputs: [{ name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ name: '', type: 'bool' }], stateMutability: 'nonpayable' },
    { type: 'function', name: 'transferFrom', inputs: [{ name: 'from', type: 'address' }, { name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ name: '', type: 'bool' }], stateMutability: 'nonpayable' },
    { type: 'function', name: 'totalSupply', inputs: [], outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view' },
    { type: 'function', name: 'allowance', inputs: [{ name: 'owner', type: 'address' }, { name: 'spender', type: 'address' }], outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view' },
    { type: 'function', name: 'decimals', inputs: [], outputs: [{ name: '', type: 'uint8' }], stateMutability: 'view' },
    { type: 'function', name: 'symbol', inputs: [], outputs: [{ name: '', type: 'string' }], stateMutability: 'view' },
    { type: 'event', name: 'Transfer', inputs: [{ name: 'from', type: 'address', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'value', type: 'uint256', indexed: false }] },
    { type: 'event', name: 'Approval', inputs: [{ name: 'owner', type: 'address', indexed: true }, { name: 'spender', type: 'address', indexed: true }, { name: 'value', type: 'uint256', indexed: false }] },
    { type: 'function', name: 'permit', inputs: [{ name: 'owner', type: 'address' }, { name: 'spender', type: 'address' }, { name: 'value', type: 'uint256' }, { name: 'deadline', type: 'uint256' }, { name: 'v', type: 'uint8' }, { name: 'r', type: 'bytes32' }, { name: 's', type: 'bytes32' }], outputs: [], stateMutability: 'nonpayable' },
    { type: 'function', name: 'nonces', inputs: [{ name: 'owner', type: 'address' }], outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view' },
  ]
  writeAbiFile('ERC20', erc20Abi)

  // Read deployment files for all known networks
  interface NetworkAddresses {
    remitChain: string
    escrowVault: string
    kycRegistry: string
    timelockAddress: string
    qusd: string
    feeTreasury: string
    deployedAtBlock: number
    deployed: boolean
  }

  const networkData: Record<number, NetworkAddresses> = {
    31337: {
      remitChain:      '0x0000000000000000000000000000000000000000',
      escrowVault:     '0x0000000000000000000000000000000000000000',
      kycRegistry:     '0x0000000000000000000000000000000000000000',
      timelockAddress: '0x0000000000000000000000000000000000000000',
      qusd:            '0x0000000000000000000000000000000000000000',
      feeTreasury:     '0x0000000000000000000000000000000000000000',
      deployedAtBlock: 0,
      deployed: false,
    },
    1983: {
      remitChain:      '0x0000000000000000000000000000000000000000',
      escrowVault:     '0x0000000000000000000000000000000000000000',
      kycRegistry:     '0x0000000000000000000000000000000000000000',
      timelockAddress: '0x0000000000000000000000000000000000000000',
      qusd:            '0x56AD1E16394Ae6F8B3204b07e988f9d37497e58f',
      feeTreasury:     '0x3660362BeB3A95CE16D981e7D30E1e025E741393',
      deployedAtBlock: 6444615,
      deployed: false,
    },
    1990: {
      remitChain:      '0x0000000000000000000000000000000000000000',
      escrowVault:     '0x0000000000000000000000000000000000000000',
      kycRegistry:     '0x0000000000000000000000000000000000000000',
      timelockAddress: '0x0000000000000000000000000000000000000000',
      qusd:            MAINNET_QUSD_PLACEHOLDER,
      feeTreasury:     '0x3660362BeB3A95CE16D981e7D30E1e025E741393',
      deployedAtBlock: 8537358,
      deployed: false,
    },
  }

  let feeBps = 10
  const networksFound: string[] = []

  for (const network of NETWORKS) {
    const deployFile = path.join(DEPLOY_DIR, network.file)
    if (!fs.existsSync(deployFile)) {
      console.log(`  ⚠ ${network.file} not found — skipping ${network.label}`)
      continue
    }

    const dep: DeploymentFile = JSON.parse(fs.readFileSync(deployFile, 'utf-8'))
    feeBps = dep.config.initialFeeBps ?? feeBps

    networkData[network.chainId] = {
      remitChain:      dep.contracts.RemitChain,
      escrowVault:     dep.contracts.EscrowVault,
      kycRegistry:     dep.contracts.KYCRegistry,
      timelockAddress: dep.contracts.TimelockController,
      qusd:            dep.config.qusd,
      feeTreasury:     dep.config.feeTreasury,
      // Fall back to whatever was already known if the deployment file predates
      // the `deployedAtBlock` field.
      deployedAtBlock: dep.deployedAtBlock ?? networkData[network.chainId]?.deployedAtBlock ?? 0,
      deployed: true,
    }

    networksFound.push(`${network.label} (${network.chainId})`)
    console.log(`  ✓ ${network.file} (${network.label})`)
  }

  // Describe the mainnet token truthfully rather than asserting it is the
  // official stablecoin. The previous template hard-coded
  // "// Official QUSDC on QIE mainnet" next to whatever address the deployment
  // happened to carry — which was MockQUSD, so the file asserted the opposite
  // of the truth.
  const mainnetToken = networkData[1990].qusd.toLowerCase()
  const testTokenWarning = KNOWN_TEST_TOKENS[mainnetToken]
  const mainnetTokenNote = testTokenWarning
    ? ` // WARNING: ${testTokenWarning}`
    : ''

  if (testTokenWarning) {
    console.log('')
    console.warn(`  ⚠ MAINNET TOKEN IS A TEST TOKEN: ${testTokenWarning}`)
    console.warn('    Real value cannot be settled against it. Redeploy against the')
    console.warn('    real stablecoin before launch — see LAUNCH.md §1.')
  }

  // Write contracts.ts with the chain-keyed address map
  const contractsContent = `// Auto-generated by scripts/sync-abis.ts — DO NOT EDIT MANUALLY
// Networks: ${networksFound.join(', ') || 'none yet'}
// Regenerate: pnpm sync:abis

import { RemitChainAbi } from './abis/RemitChain'
import { EscrowVaultAbi } from './abis/EscrowVault'
import { KYCRegistryAbi } from './abis/KYCRegistry'
import { ERC20Abi } from './abis/ERC20'

export { RemitChainAbi, EscrowVaultAbi, KYCRegistryAbi, ERC20Abi }

// ─── Per-chain contract addresses ───────────────────────────────────────────
const CONTRACT_ADDRESSES = {
  // Anvil (chainId 31337) — local development, written by DeployLocal.s.sol
  31337: {
    remitChain:      '${networkData[31337].remitChain}' as const,
    escrowVault:     '${networkData[31337].escrowVault}' as const,
    kycRegistry:     '${networkData[31337].kycRegistry}' as const,
    timelockAddress: '${networkData[31337].timelockAddress}' as const,
    qusd:            '${networkData[31337].qusd}' as const,
    feeTreasury:     '${networkData[31337].feeTreasury}' as const,
  },
  // QIE Testnet (chainId 1983)
  1983: {
    remitChain:      '${networkData[1983].remitChain}' as const,
    escrowVault:     '${networkData[1983].escrowVault}' as const,
    kycRegistry:     '${networkData[1983].kycRegistry}' as const,
    timelockAddress: '${networkData[1983].timelockAddress}' as const,
    qusd:            '${networkData[1983].qusd}' as const,
    feeTreasury:     '${networkData[1983].feeTreasury}' as const,
  },
  // QIE Mainnet (chainId 1990) — populated after: forge script Deploy.s.sol --rpc-url qie_mainnet --broadcast
  1990: {
    remitChain:      '${networkData[1990].remitChain}' as const,
    escrowVault:     '${networkData[1990].escrowVault}' as const,
    kycRegistry:     '${networkData[1990].kycRegistry}' as const,
    timelockAddress: '${networkData[1990].timelockAddress}' as const,
    qusd:            '${networkData[1990].qusd}' as const,${mainnetTokenNote}
    feeTreasury:     '${networkData[1990].feeTreasury}' as const,
  },
} as const

type SupportedChainId = keyof typeof CONTRACT_ADDRESSES

// Default to mainnet when NEXT_PUBLIC_CHAIN_ID is unset, which happens during
// a CI build with no environment. Throwing here would fail the build at module
// load, before any route could report a useful error.
const _rawChainId = Number(process.env.NEXT_PUBLIC_CHAIN_ID)
const _chainId: SupportedChainId =
  _rawChainId === 1983 ? 1983 : _rawChainId === 31337 ? 31337 : 1990

function getContracts() {
  const addrs = CONTRACT_ADDRESSES[_chainId]
  if (!addrs) {
    console.error(
      \`[contracts] No addresses configured for chain \${_chainId}. \` +
      \`Supported: \${Object.keys(CONTRACT_ADDRESSES).join(', ')}. Falling back to mainnet.\`
    )
    return CONTRACT_ADDRESSES[1990]
  }
  return addrs
}

const contracts = getContracts()

export const REMITCHAIN_ADDRESS   = contracts.remitChain
export const ESCROW_VAULT_ADDRESS = contracts.escrowVault
export const KYC_REGISTRY_ADDRESS = contracts.kycRegistry
export const TIMELOCK_ADDRESS     = contracts.timelockAddress
export const QUSD_ADDRESS         = contracts.qusd
export const FEE_TREASURY_ADDRESS = contracts.feeTreasury

// ─── Contract Config ─────────────────────────────────────────────────────────

/** Fee in basis points (10 = 0.1%) */
export const FEE_BPS = ${feeBps} as const

/** QUSD/QUSDC decimals (6 on both testnet and mainnet) */
export const QUSD_DECIMALS = 6 as const

/** Whether the app is targeting a production mainnet */
export const IS_MAINNET = _chainId === 1990

/**
 * Block each deployment went live at — where the event listener starts from.
 *
 * Written from the deployedAtBlock field in the contracts/deployments files.
 * This used to be a hand-maintained table in lib/events/listener.ts, so a
 * redeploy that nobody remembered to follow up on left the listener scanning
 * the previous contract's history from its old start height.
 *
 * The value is the block the deploy script simulated against, which is at or
 * just before the block the contracts actually landed in. Starting a block or
 * two early costs one wasted scan; starting late silently loses events.
 */
export const DEPLOYMENT_BLOCKS: Record<number, bigint> = {
  31337: ${networkData[31337].deployedAtBlock}n,
  1983: ${networkData[1983].deployedAtBlock}n,
  1990: ${networkData[1990].deployedAtBlock}n,
}
`

  fs.writeFileSync(CONTRACTS_FILE, contractsContent, 'utf-8')
  console.log('  ✓ lib/contracts.ts')
  console.log('\n✅ ABI sync complete.\n')
}

main()
