#!/usr/bin/env tsx
/**
 * sync-abis.ts
 * Reads compiled Foundry artifacts + deployment addresses,
 * writes type-safe ABI files to lib/abis/ and lib/contracts.ts.
 * Run: pnpm sync:abis
 */

import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(__dirname, '../..')
const OUT_DIR = path.join(ROOT, 'contracts/out')
const DEPLOY_FILE = path.join(ROOT, 'contracts/deployments/qie_testnet.json')
const ABIS_DIR = path.join(__dirname, '../lib/abis')
const CONTRACTS_FILE = path.join(__dirname, '../lib/contracts.ts')

function readAbi(contractDir: string, contractName: string): unknown[] {
  const jsonPath = path.join(OUT_DIR, contractDir, `${contractName}.json`)
  if (!fs.existsSync(jsonPath)) {
    throw new Error(`Artifact not found: ${jsonPath}`)
  }
  const artifact = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'))
  return artifact.abi
}

function writeAbiFile(name: string, abi: unknown[]): void {
  const content = `// Auto-generated by scripts/sync-abis.ts — DO NOT EDIT MANUALLY
// Source: contracts/out/${name}.sol/${name}.json

export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;
`
  fs.writeFileSync(path.join(ABIS_DIR, `${name}.ts`), content, 'utf-8')
  console.log(`  ✓ lib/abis/${name}.ts`)
}

function main(): void {
  // Ensure output directory exists
  fs.mkdirSync(ABIS_DIR, { recursive: true })

  console.log('\n🔄 Syncing ABIs from contracts/out/...\n')

  // Extract and write the three core contract ABIs
  const remitChainAbi = readAbi('RemitChain.sol', 'RemitChain')
  writeAbiFile('RemitChain', remitChainAbi)

  const escrowVaultAbi = readAbi('EscrowVault.sol', 'EscrowVault')
  writeAbiFile('EscrowVault', escrowVaultAbi)

  const kycRegistryAbi = readAbi('KYCRegistry.sol', 'KYCRegistry')
  writeAbiFile('KYCRegistry', kycRegistryAbi)

  // Minimal ERC20 ABI (only what we use)
  const erc20Abi = [
    {
      type: 'function',
      name: 'balanceOf',
      inputs: [{ name: 'account', type: 'address' }],
      outputs: [{ name: '', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'approve',
      inputs: [
        { name: 'spender', type: 'address' },
        { name: 'amount', type: 'uint256' },
      ],
      outputs: [{ name: '', type: 'bool' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'allowance',
      inputs: [
        { name: 'owner', type: 'address' },
        { name: 'spender', type: 'address' },
      ],
      outputs: [{ name: '', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'decimals',
      inputs: [],
      outputs: [{ name: '', type: 'uint8' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'symbol',
      inputs: [],
      outputs: [{ name: '', type: 'string' }],
      stateMutability: 'view',
    },
    {
      type: 'event',
      name: 'Transfer',
      inputs: [
        { name: 'from', type: 'address', indexed: true },
        { name: 'to', type: 'address', indexed: true },
        { name: 'value', type: 'uint256', indexed: false },
      ],
    },
    {
      type: 'event',
      name: 'Approval',
      inputs: [
        { name: 'owner', type: 'address', indexed: true },
        { name: 'spender', type: 'address', indexed: true },
        { name: 'value', type: 'uint256', indexed: false },
      ],
    },
    {
      type: 'function',
      name: 'permit',
      inputs: [
        { name: 'owner', type: 'address' },
        { name: 'spender', type: 'address' },
        { name: 'value', type: 'uint256' },
        { name: 'deadline', type: 'uint256' },
        { name: 'v', type: 'uint8' },
        { name: 'r', type: 'bytes32' },
        { name: 's', type: 'bytes32' },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'nonces',
      inputs: [{ name: 'owner', type: 'address' }],
      outputs: [{ name: '', type: 'uint256' }],
      stateMutability: 'view',
    },
  ]
  writeAbiFile('ERC20', erc20Abi)

  // Read deployment addresses
  if (!fs.existsSync(DEPLOY_FILE)) {
    throw new Error(`Deployment file not found: ${DEPLOY_FILE}`)
  }
  const deployments = JSON.parse(fs.readFileSync(DEPLOY_FILE, 'utf-8'))
  const { contracts, config } = deployments

  // Write contracts.ts
  const contractsContent = `// Auto-generated by scripts/sync-abis.ts — DO NOT EDIT MANUALLY
// Source: contracts/deployments/qie_testnet.json

import { RemitChainAbi } from './abis/RemitChain'
import { EscrowVaultAbi } from './abis/EscrowVault'
import { KYCRegistryAbi } from './abis/KYCRegistry'
import { ERC20Abi } from './abis/ERC20'

export { RemitChainAbi, EscrowVaultAbi, KYCRegistryAbi, ERC20Abi }

// ─── Contract Addresses (QIE Testnet, Chain ID 1983) ────────────────────────

export const REMITCHAIN_ADDRESS = '${contracts.RemitChain}' as const
export const ESCROW_VAULT_ADDRESS = '${contracts.EscrowVault}' as const
export const KYC_REGISTRY_ADDRESS = '${contracts.KYCRegistry}' as const
export const TIMELOCK_ADDRESS = '${contracts.TimelockController}' as const
export const QUSD_ADDRESS = '${config.qusd}' as const
export const FEE_TREASURY_ADDRESS = '${config.feeTreasury}' as const

// ─── Contract Config ─────────────────────────────────────────────────────────

/** Fee in basis points (10 = 0.1%) */
export const FEE_BPS = ${config.initialFeeBps} as const

/** QUSD decimals */
export const QUSD_DECIMALS = 6 as const
`

  fs.writeFileSync(CONTRACTS_FILE, contractsContent, 'utf-8')
  console.log('  ✓ lib/contracts.ts')
  console.log('\n✅ ABI sync complete.\n')
}

main()
