// Auto-generated by scripts/sync-abis.ts — DO NOT EDIT MANUALLY
// Networks: QIE Testnet (1983), QIE Mainnet (1990)
// Regenerate: pnpm sync:abis

import { RemitChainAbi } from './abis/RemitChain'
import { EscrowVaultAbi } from './abis/EscrowVault'
import { KYCRegistryAbi } from './abis/KYCRegistry'
import { ERC20Abi } from './abis/ERC20'

export { RemitChainAbi, EscrowVaultAbi, KYCRegistryAbi, ERC20Abi }

// ─── Per-chain contract addresses ───────────────────────────────────────────
const CONTRACT_ADDRESSES = {
  // QIE Testnet (chainId 1983)
  1983: {
    remitChain:      '0xAf4230B61C3416DB65000B7E6A5F8A3E7568304B' as const,
    escrowVault:     '0x3003E7d75477c4F6836Ec117f6e9C1202e09Da84' as const,
    kycRegistry:     '0xB388C8cdF22Bd89F0110620A0B557baA5d9D6eF1' as const,
    timelockAddress: '0xf20b5D93fDbec6B5cc8dC6d71Ad24D2C4641Ab41' as const,
    qusd:            '0x56AD1E16394Ae6F8B3204b07e988f9d37497e58f' as const,
    feeTreasury:     '0x3660362BeB3A95CE16D981e7D30E1e025E741393' as const,
  },
  // QIE Mainnet (chainId 1990) — populated after: forge script Deploy.s.sol --rpc-url qie_mainnet --broadcast
  1990: {
    remitChain:      '0x7463883Edb58Df1213BF177ea9CeC9A9E1531b0A' as const,
    escrowVault:     '0x1fE0132c7A95353aA6D7c8D4D5F97E2A0EA3B65D' as const,
    kycRegistry:     '0x981A7b9ab10619C4550CA3A3705C294157ceB5eA' as const,
    timelockAddress: '0xb5E17f1A16fB35fBA0a7195cbb4eabDFc704Bfcf' as const,
    qusd:            '0x9b5D310a92F05C3714E4163e43f226c7A6FB0827' as const, // MockQUSD
    feeTreasury:     '0x3660362BeB3A95CE16D981e7D30E1e025E741393' as const,
  },
} as const

type SupportedChainId = keyof typeof CONTRACT_ADDRESSES

const _chainId = Number(process.env.NEXT_PUBLIC_CHAIN_ID) as SupportedChainId

function getContracts() {
  const addrs = CONTRACT_ADDRESSES[_chainId]
  if (!addrs) {
    throw new Error(
      `[contracts] No addresses configured for chain ${_chainId}. ` +
      `Supported: ${Object.keys(CONTRACT_ADDRESSES).join(', ')}.`
    )
  }
  return addrs
}

const contracts = getContracts()

export const REMITCHAIN_ADDRESS   = contracts.remitChain
export const ESCROW_VAULT_ADDRESS = contracts.escrowVault
export const KYC_REGISTRY_ADDRESS = contracts.kycRegistry
export const TIMELOCK_ADDRESS     = contracts.timelockAddress
export const QUSD_ADDRESS         = contracts.qusd
export const FEE_TREASURY_ADDRESS = contracts.feeTreasury

// ─── Contract Config ─────────────────────────────────────────────────────────

/** Fee in basis points (10 = 0.1%) */
export const FEE_BPS = 10 as const

/** QUSD/QUSDC decimals (6 on both testnet and mainnet) */
export const QUSD_DECIMALS = 6 as const

/** Whether the app is targeting a production mainnet */
export const IS_MAINNET = _chainId === 1990
