// Auto-generated by scripts/sync-abis.ts — DO NOT EDIT MANUALLY
// Networks: Anvil (local) (31337), QIE Testnet (1983), QIE Mainnet (1990)
// Regenerate: pnpm sync:abis

import { RemitChainAbi } from './abis/RemitChain'
import { EscrowVaultAbi } from './abis/EscrowVault'
import { KYCRegistryAbi } from './abis/KYCRegistry'
import { ERC20Abi } from './abis/ERC20'

export { RemitChainAbi, EscrowVaultAbi, KYCRegistryAbi, ERC20Abi }

// ─── Per-chain contract addresses ───────────────────────────────────────────
const CONTRACT_ADDRESSES = {
  // Anvil (chainId 31337) — local development, written by DeployLocal.s.sol
  31337: {
    remitChain:      '0xa513E6E4b8f2a923D98304ec87F64353C4D5C853' as const,
    escrowVault:     '0x0165878A594ca255338adfa4d48449f69242Eb8F' as const,
    kycRegistry:     '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707' as const,
    timelockAddress: '0x0000000000000000000000000000000000000000' as const,
    qusd:            '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9' as const,
    feeTreasury:     '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65' as const,
  },
  // QIE Testnet (chainId 1983)
  1983: {
    remitChain:      '0xAf4230B61C3416DB65000B7E6A5F8A3E7568304B' as const,
    escrowVault:     '0x3003E7d75477c4F6836Ec117f6e9C1202e09Da84' as const,
    kycRegistry:     '0xB388C8cdF22Bd89F0110620A0B557baA5d9D6eF1' as const,
    timelockAddress: '0xf20b5D93fDbec6B5cc8dC6d71Ad24D2C4641Ab41' as const,
    qusd:            '0x56AD1E16394Ae6F8B3204b07e988f9d37497e58f' as const,
    feeTreasury:     '0x3660362BeB3A95CE16D981e7D30E1e025E741393' as const,
  },
  // QIE Mainnet (chainId 1990) — populated after: forge script Deploy.s.sol --rpc-url qie_mainnet --broadcast
  1990: {
    remitChain:      '0x56c650167e2D3a20A1131bC3b9e23449bC604AEa' as const,
    escrowVault:     '0xbFC6e4dc09a59F9341EfACA72FFfff4ABF2e03FA' as const,
    kycRegistry:     '0xaab80c35136e336F3D0fCf113bD1A092Bf206832' as const,
    timelockAddress: '0xD26Dc2EFD20622867EF9e2C238047490652511D3' as const,
    qusd:            '0x9b5D310a92F05C3714E4163e43f226c7A6FB0827' as const, // WARNING: MockQUSD — owner-mintable test token, NOT redeemable
    feeTreasury:     '0x3660362BeB3A95CE16D981e7D30E1e025E741393' as const,
  },
} as const

type SupportedChainId = keyof typeof CONTRACT_ADDRESSES

// Default to mainnet when NEXT_PUBLIC_CHAIN_ID is unset, which happens during
// a CI build with no environment. Throwing here would fail the build at module
// load, before any route could report a useful error.
const _rawChainId = Number(process.env.NEXT_PUBLIC_CHAIN_ID)
const _chainId: SupportedChainId =
  _rawChainId === 1983 ? 1983 : _rawChainId === 31337 ? 31337 : 1990

function getContracts() {
  const addrs = CONTRACT_ADDRESSES[_chainId]
  if (!addrs) {
    console.error(
      `[contracts] No addresses configured for chain ${_chainId}. ` +
      `Supported: ${Object.keys(CONTRACT_ADDRESSES).join(', ')}. Falling back to mainnet.`
    )
    return CONTRACT_ADDRESSES[1990]
  }
  return addrs
}

const contracts = getContracts()

export const REMITCHAIN_ADDRESS   = contracts.remitChain
export const ESCROW_VAULT_ADDRESS = contracts.escrowVault
export const KYC_REGISTRY_ADDRESS = contracts.kycRegistry
export const TIMELOCK_ADDRESS     = contracts.timelockAddress
export const QUSD_ADDRESS         = contracts.qusd
export const FEE_TREASURY_ADDRESS = contracts.feeTreasury

// ─── Contract Config ─────────────────────────────────────────────────────────

/** Fee in basis points (10 = 0.1%) */
export const FEE_BPS = 10 as const

/** QUSD/QUSDC decimals (6 on both testnet and mainnet) */
export const QUSD_DECIMALS = 6 as const

/** Whether the app is targeting a production mainnet */
export const IS_MAINNET = _chainId === 1990
